name: Build and deploy Docker image

on:
  push:
    tags:
      - "*"

jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      -
        name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: lts.Dockerfile
          tags: |
            ghcr.io/johnbcodes/node-rust:lts-latest
            ghcr.io/johnbcodes/node-rust:lts-${{ github.ref_name }}
          push: true
          build-args: |
            RUST_VERSION=${{ github.ref_name }}
            RUSTUP_VERSION=1.27
      -
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: current.Dockerfile
          tags: |
            ghcr.io/johnbcodes/node-rust:current-latest
            ghcr.io/johnbcodes/node-rust:current-${{ github.ref_name }}
          push: true
